#Eric Jacobson
#erjacobs@redhat.com
#29 June 2018
#
#Configuration file specifying which endpoints to watch in OpenStack 
#
#Put desired endpoints in list below:
#---
endpoints:
  - openstack port delete

#---

