#Eric Jacobson
#erjacobs@redhat.com
#29 June 2018
#
#Configuration file specifying which endpoints to watch in OpenStack 
#
#Put endpoints in list below:
#---
neutron:
  - port

octavia:
  - loadbalancer
  - listener
  - pool
  - member

nova:
  - compute
#---

